% IACR Transactions CLASS DOCUMENTATION
% Written by Gaetan Leurent gaetan.leurent@inria.fr (2016-2018)
%
% To the extent possible under law, the author(s) have dedicated all
% copyright and related and neighboring rights to this software to the
% public domain worldwide. This software is distributed without any
% warranty.
%
% You should have received a copy of the CC0 Public Domain Dedication
% along with this software. If not, see
% <http://creativecommons.org/publicdomain/zero/1.0/>.

DOCUMENTCLASS

\usepackage[utf8]{inputenc}
\usepackage{lipsum}

\author{Author One\inst{1} \and Author Two\inst{2}}
\institute{Test Institut, Germany, \email{test.me@example.de} \and
           Institute de Teste, France, \email{test.me@example.fr}}
\title[\texttt{iacrtans} class tests]{\publname}

\begin{document}

\maketitle

% use optional argument because the \LaTeX command breaks the PDF keywords
\keywords[\publname, Test]{\publname{} \and Test}

\begin{abstract}
  This tests the class options.
\end{abstract}

\tableofcontents{}

\section*{Introduction}

\lipsum

\end{document}
